#!/bin/sh
gitls() {
    git ls-tree --full-tree --name-only -r HEAD > $1
}

# Generate git tracked files list
cd ~/.dotlib
gitls /tmp/dotlib.txt
cd ~
gitls /tmp/dotfiles.txt

# Diff them
diff -u --color /tmp/dotlib.txt /tmp/dotfiles.txt

# Cleanup
rm /tmp/dotlib.txt /tmp/dotfiles.txt
