#!/usr/bin/env bash

if [[ -z "$SSH_TTY" ]]; then
    transfermode='file'
else
    transfermode='stream'
fi
kitty +kitten icat --clear --stdin no --silent --transfer-mode "$transfermode" < /dev/null > /dev/tty
