#!/usr/bin/env bash
# https://www.reddit.com/r/KittyTerminal/comments/132n4p5/any_lf_file_manager_users_how_to_preview_pdfs_as/
file=$1
w=$2
h=$3
x=$4
y=$5

# mimetype="$( file -Lb --mime-type "$file")"
mimetype="$( file --dereference --brief --mime-type -- "${file}" )"
filename=$(basename $(echo "$file" | tr ' ' '_'))


function kitty_icat() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}


case "${mimetype}" in
    image/*)
        kitty_icat "$file"
        ;;
    *pdf)
        if [[ ! -f "/tmp/$filename.png" ]]; then
            pdftoppm -f 1 -l 1 "$file" > "/tmp/$filename.png"
        fi
        kitty_icat "/tmp/$filename.png"
        ;;
    audio/*)
        if [[ ! -f "/tmp/$filename.jpg" ]]; then
            ffmpeg -i "$file" -an -c:v copy "/tmp/$filename.jpg"
        fi
        kitty_icat "/tmp/$filename.jpg"
        ;;
    video/*)
        if [[ ! -f "/tmp/$filename.jpg" ]]; then
            ffmpeg -i "$file" -vf "thumbnail" -frames:v 1 "/tmp/$filename.jpg"
        fi
        kitty_icat "/tmp/$filename.jpg"
        ;;
    *zip | *tar | *rar | *x-xz)
        # sudo apt install atool
        als "$file" | awk '{print $NF}'
        exit 1
        ;;
    *)
        cat "$file"
        ;;
esac

exit 1
