#!/usr/bin/env bash
# Ref:
# https://www.reddit.com/r/KittyTerminal/comments/132n4p5/any_lf_file_manager_users_how_to_preview_pdfs_as/
# https://github.com/rafi/.config/blob/master/lf/preview

# NOTE:
# For lf,
# `exit 1` means lf will not cache the preview result, and will run the cleaner script. Kitty need to exit 1 to solve the picture still remains after preview.
# `exit 0` means lf will cache the preview result and will acclerate the next time preview for same file. If not previewed by kitty, we can exit 0.

FILE="$(realpath "$1")"
W=$2
H=$(echo "$3 * 0.99 / 1" | bc)  # 99% of the height
X=$4
Y=$5

# _TMPFILENAME="$(basename "$FILE" | tr ' ' '__' | tr '.' '_')".png
_TMPFILENAME="$(sha256sum "$FILE" | awk '{print $1}')".png
_TMPFILEDIR=/tmp/lf_img"$(dirname "$FILE")"
mkdir -p "$_TMPFILEDIR"
TMPFILEPATH="${_TMPFILEDIR}/${_TMPFILENAME}"

# FILE_EXTENSION="${FILE##*.}"
# FILE_EXTENSION_LOWER="$(printf "%s" "${FILE_EXTENSION}" | tr '[:upper:]' '[:lower:]')"
MIMETYPE="$(file --dereference --brief --mime-type -- "$FILE")"


function image_previewer() {
    local experimental  # 0 is true, 1 is false. Default 1 for false.
    experimental=$([[ -n "$2" ]] && echo "$2" || echo 1)

    local transfer_mode  # Only when ssh, use stream mode. If local, use file mode.
    transfer_mode=$([[ -n "$SSH_TTY" ]] && echo 'stream' || echo 'file')

    if [[ "$TERM" == 'xterm-kitty' || (-n "$TMUX" && "$experimental" -eq 0) ]]; then
        kitty +kitten icat --silent --stdin no --transfer-mode "$transfer_mode"  --place "${W}x${H}@${X}x${Y}" "$1" < /dev/null > /dev/tty
        if [ $? -eq 0 ]; then
            exit 1
        fi
    fi

    # For alacritty, I set alacritty default $TERM to xterm-256color
    # But in tmux, tmux will change the $TERM to screen-256color, this is also I specifically made it.
    # However, if one day in the future, I set tmux $TERM to xterm-256color, it will cause the picture to be displayed incorrectly.
    # So now I have to add the condition of -z "$TMUX" to prevent things happening in the future, even if this is an accidental case.
    if [[ ("$TERM" == 'xterm-256color' && -z "$TMUX") || "$TERM" == 'st-256color' || "$TERM" == 'wezterm' ]]; then
        chafa -f sixels -s "$W"x"$H" "$1" --polite on
        if [ $? -eq 0 ]; then
            exit 0
        fi
    fi

    # fallback
    chafa -f symbols -s "$W"x"$H" "$1"
    if [ $? -eq 0 ]; then
        exit 0
    fi

    # fallback if no chafa
    cat "$1"
    exit 0
}


function handle_extension() {
    case "$FILE" in
        *.nii | *.nii.gz)
            # git clone git@git.zhlh6.cn:ysl2/niicat.git ~/.vocal/niicat
            if [[ ! -f "$TMPFILEPATH" ]]; then
                niicat "$FILE" "$TMPFILEPATH"
            fi
            # image_previewer "$TMPFILEPATH" 0
            image_previewer "$TMPFILEPATH"
            ;;
        *.six | *.sixel)
            if [[ ! -f "$TMPFILEPATH" ]]; then
                sixel2png "$FILE" > "$TMPFILEPATH"
            fi
            image_previewer "$TMPFILEPATH"
            ;;
        *.pkl)
            python -c "import pickle; from pprint import pprint; p = pickle.load(open('$FILE', 'rb')); pprint(p)"
            ;;
    esac
    # WARNING: Do not add any exit value here!
}


function handle_mime() {
    case "$MIMETYPE" in
        image/*)
            image_previewer "$FILE"
            ;;
        *pdf)
            if [[ ! -f "$TMPFILEPATH" ]]; then
                pdftoppm -f 1 -l 1 -png "$FILE" > "$TMPFILEPATH"
            fi
            image_previewer "$TMPFILEPATH"
            ;;
        audio/*)
            if [[ ! -f "$TMPFILEPATH" ]]; then
                ffmpeg -i "$FILE" -filter_complex "showwavespic=s=640x480" -frames:v 1 "$TMPFILEPATH"
            fi
            image_previewer "$TMPFILEPATH"
            ;;
        video/*)
            if [[ ! -f "$TMPFILEPATH" ]]; then
                # sudo apt install -y ffmpeg
                ffmpeg -i "$FILE" -vf "thumbnail" -frames:v 1 "$TMPFILEPATH"
            fi
            image_previewer "$TMPFILEPATH"
            ;;
        *zip | *tar | *rar | *x-xz)
            # sudo apt install atool
            als "$FILE" | awk '{print $NF}'
            exit 0
            ;;
        *)
            cat "$FILE"
            exit 0
            ;;
    esac
    # WARNING: Do not add any exit value here!
}


function main() {
    handle_extension
    handle_mime
}


main "$@"
