gui:
  language: en
  # https://github.com/catppuccin/lazygit/blob/d3c95a67ea3f778f7705d8ef814f87ac5213436d/themes-mergable/frappe/flamingo.yml
  theme:
    activeBorderColor:
      - '#eebebe'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#eebebe'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'

  authorColors:
    '*': '#babbf1'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  disableForcePushing: true
keybinding:
    universal:
        quit-alt1: <disabled>
        # return: <c-c>
