# https://blog.csdn.net/m0_47627464/article/details/113790309

# 垂直候选列表
Vertical Candidate List=False

# 按屏幕 DPI 使用
#PerScreenDPI=True
PerScreenDPI=False

# Font (设置成你喜欢的字体)
Font="Noto Sans Regular 16"

# 主题
#Theme=Material-Color-DeepPurple

# 提供几个主题名(良心的博主直接全打好了，直接去注释就好了，还不点赞):
# Theme=Material-Color-Pink
# Theme=Material-Color-Blue
# Theme=Material-Color-Brown
# Theme=Material-Color-DeepPurple
# Theme=Material-Color-Indigo
# Theme=Material-Color-Red
# Theme=Material-Color-Teal
# Theme=Material-Color-Black
# Theme=Material-Color-Orange
# Theme=Material-Color-SakuraPink
