#! /bin/bash
# 该脚本用于处理yay安装软件时，由github下载缓慢甚至无法下载的问题
# 检测域名是不是github，如果是，则替换为镜像网站，依旧使用curl下载
# 如果不是github则采用axel代替curl进行15线程下载
# 实验用链接：
# https://download.fastgit.org/beekeeper-studio/beekeeper-studio/releases/download/v1.6.11/beekeeper-studio_1.6.11_amd64.deb
# https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v1.6.11/beekeeper-studio_1.6.11_amd64.deb

domin=`echo $2 | cut -f3 -d'/'`;
others=`echo $2 | cut -f4- -d'/'`;
case "$domin" in 
    "github.com")
    url="https://hub.fastgit.org/"$others;
    echo "download from github mirror $url";
    # /usr/bin/curl -gqb "" -fLC - --retry 3 --retry-delay 3 -o $1 $url;
	/usr/bin/aria2c --allow-overwrite=true --always-resume=false --auto-file-renaming=false --check-integrity=true --conditional-get=true --file-allocation=none --log-level=error --continue=true --max-concurrent-downloads=100 --max-connection-per-server=16 --min-split-size=1M --remote-time=true --show-console-readout=true -o $1 $url;
    ;;
    *)
    url=$2;
    # /usr/bin/aria2c -x16 -o $1 $url;
	/usr/bin/aria2c --allow-overwrite=true --always-resume=false --auto-file-renaming=false --check-integrity=true --conditional-get=true --file-allocation=none --log-level=error --continue=true --max-concurrent-downloads=100 --max-connection-per-server=16 --min-split-size=1M --remote-time=true --show-console-readout=true -o $1 $url;
    ;;
esac
