version: "3.3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Yu970629!
      - TZ=Asia/Shanghai
    volumes:
      - ~/my-docker/my-docker-volumes/my-mysql/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - 8080:8080
    restart: unless-stopped

